id: IA6C58AA8
legacy_id: null
ocr_import_info:
  bdrc_scan_id: W30305
  source: bdrc.io
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  ocr_info: {}
  op_import_options: {}
  op_import_version: 0.9.5
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-10-19T04:56:14.597159+00:00'
last_modified: '2022-10-19T04:56:14.597175+00:00'
parser: null
source_metadata:
  id: http://purl.bdrc.io/resource/W30305
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessFairUse
  reproduction_of: http://purl.bdrc.io/resource/MW30305
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་ལ་འཇུག་པའི་སྤྱི་དོན་དགོངས་པ་རབ་གསལ་གྱི་རྒྱན།
  languages:
  - bo
  author: པཎ་ཆེན་བློ་གྲོས་ལེགས་བཟང་།
statistics:
  ocr_word_mean_confidence_index: 0.9965359021027989
  ocr_word_median_confidence_index: 1.0
quality: null
bases:
  I1CZ2458:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2458
      total_pages: 434
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ2458.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9965359021027989
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
